# This Docker setup is meant to be used during development.
# It is not recommended to use this file for running the
# project in production.

version: '3'

services:
  database:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: rtmpie
      MYSQL_DATABASE: rtmpie
    volumes:
      - database:/var/lib/mysql
    ports: [3306]

  mercure:
    image: dunglas/mercure
    environment:
      - ALLOW_ANONYMOUS=1
      - CORS_ALLOWED_ORIGINS=*
      - JWT_KEY=!ChangeMe!
      - PUBLISH_ALLOWED_ORIGINS=*
    ports:
      - 8008:80

  rtmp:
#    image: ngrie/nginx-rtmp
    build:
      context: ./docker/nginx-rtmp
    volumes:
      - ./rtmp_nginx_dev.conf:/etc/nginx/nginx.conf
    ports:
      - 1935:1935
      - 8081:80

volumes:
  database:
