x-service-defaults: &service-defaults
  platform: ${RTMPIE_DOCKER_PLATFORM:-linux/arm64}

services:
  php:
    <<: *service-defaults
    image: ghcr.io/ngrie/rtmpie/php:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: rtmpie-php
    pull_policy: build
    restart: unless-stopped
    environment:
      APP_SECRET: ${RTMPIE_APP_SECRET}
      DATABASE_URL: mysql://root:${RTMPIE_DATABASE_PASSWORD}@database:3306/rtmpie?serverVersion=mariadb-10.4.12
      MERCURE_PUBLIC_URL: ${RTMPIE_HTTP_SCHEME}://${RTMPIE_HOSTNAME}/.well-known/mercure
      MERCURE_JWT_SECRET: ${RTMPIE_MERCURE_JWT_KEY}

  caddy:
    <<: *service-defaults
    image: ghcr.io/ngrie/rtmpie/caddy:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: rtmpie-caddy
    pull_policy: build
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      SERVER_NAME: ${RTMPIE_CADDY_SERVER_NAME}
      MERCURE_PUBLISHER_JWT_KEY: ${RTMPIE_MERCURE_JWT_KEY}
      MERCURE_SUBSCRIBER_JWT_KEY: ${RTMPIE_MERCURE_JWT_KEY}
    volumes:
      - mercure_data:/data
      - mercure_config:/config

  rtmp:
    <<: *service-defaults
    image: ghcr.io/ngrie/rtmpie/rtmp:latest
    build:
      context: ./nginx-rtmp
      dockerfile: Dockerfile
    pull_policy: build
    restart: unless-stopped
    ports:
      - "1935:1935"

  database:
    <<: *service-defaults
    image: mariadb:10.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${RTMPIE_DATABASE_PASSWORD}
      MYSQL_DATABASE: rtmpie
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
  mercure_data:
  mercure_config:
